# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Searchatlas < Formula
  desc "CLI for the SearchAtlas SEO platform"
  homepage "https://github.com/Search-Atlas-Group/searchatlas-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Search-Atlas-Group/searchatlas-cli/releases/download/v0.1.0/searchatlas_0.1.0_darwin_amd64.tar.gz"
      sha256 "8ab1061de3c06852e99c9866c6ec1df87f5089aa2dba90a94b10a39e35dcb80d"

      define_method(:install) do
        bin.install "searchatlas"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Search-Atlas-Group/searchatlas-cli/releases/download/v0.1.0/searchatlas_0.1.0_darwin_arm64.tar.gz"
      sha256 "c57db4cb30e5f8429115c85c99e823b8dd35194fd84a0704644b37fc801443a0"

      define_method(:install) do
        bin.install "searchatlas"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Search-Atlas-Group/searchatlas-cli/releases/download/v0.1.0/searchatlas_0.1.0_linux_amd64.tar.gz"
      sha256 "0448be6a138577ae59d508c36a06cb439343fc7c075250f2e8dee7749efda068"
      define_method(:install) do
        bin.install "searchatlas"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Search-Atlas-Group/searchatlas-cli/releases/download/v0.1.0/searchatlas_0.1.0_linux_arm64.tar.gz"
      sha256 "aa917d9a33c4c6a84493946d2309f041af6474e40fc6bfc3af0aa2d0f07dec72"
      define_method(:install) do
        bin.install "searchatlas"
      end
    end
  end

  test do
    system "#{bin}/searchatlas", "version"
  end
end
