# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Searchatlas < Formula
  desc "CLI for the SearchAtlas SEO platform"
  homepage "https://github.com/Search-Atlas-Group/searchatlas-cli"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Search-Atlas-Group/searchatlas-cli/releases/download/v0.1.2/searchatlas_0.1.2_darwin_amd64.tar.gz"
      sha256 "d7538dc041648aacd987dba0737353556ea9defd490cfe65c8a37a4de1ecebce"

      define_method(:install) do
        bin.install "searchatlas"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Search-Atlas-Group/searchatlas-cli/releases/download/v0.1.2/searchatlas_0.1.2_darwin_arm64.tar.gz"
      sha256 "7279ceca28bfca8a5e8f460a4c607434e8b01a4b18dc581b4a9868e4427e1d74"

      define_method(:install) do
        bin.install "searchatlas"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Search-Atlas-Group/searchatlas-cli/releases/download/v0.1.2/searchatlas_0.1.2_linux_amd64.tar.gz"
      sha256 "f5fb3e03dc8a7fdb9b5a6081c4b5ada873d18338277e8bd9cee87edc7273ad22"
      define_method(:install) do
        bin.install "searchatlas"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Search-Atlas-Group/searchatlas-cli/releases/download/v0.1.2/searchatlas_0.1.2_linux_arm64.tar.gz"
      sha256 "3e070a66c609d9f56e90b67c3f539d26e3c500774e9817fe06c818d0c8366514"
      define_method(:install) do
        bin.install "searchatlas"
      end
    end
  end

  test do
    system "#{bin}/searchatlas", "version"
  end
end
