# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Searchatlas < Formula
  desc "CLI for the SearchAtlas AI search and online visibility platform"
  homepage "https://github.com/Search-Atlas-Group/searchatlas-cli"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Search-Atlas-Group/searchatlas-cli/releases/download/v0.1.7/searchatlas_0.1.7_darwin_amd64.tar.gz"
      sha256 "e7e876994c3724f44be321a1564308693b9da6f749b3a3fb57d9882429c1c000"

      define_method(:install) do
        bin.install "searchatlas"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Search-Atlas-Group/searchatlas-cli/releases/download/v0.1.7/searchatlas_0.1.7_darwin_arm64.tar.gz"
      sha256 "aa0344d6b9f10e00e9f2dd229c1d6693d23d01e7f89f01f012396c7bed8a9258"

      define_method(:install) do
        bin.install "searchatlas"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Search-Atlas-Group/searchatlas-cli/releases/download/v0.1.7/searchatlas_0.1.7_linux_amd64.tar.gz"
      sha256 "df8e37df801ea7411fe610764f50128c085ed97b7426ad6ed842055b25ce3fc0"
      define_method(:install) do
        bin.install "searchatlas"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Search-Atlas-Group/searchatlas-cli/releases/download/v0.1.7/searchatlas_0.1.7_linux_arm64.tar.gz"
      sha256 "128e6eb84f4bf9508d1297e3395bfa96f361f80c3027db2a7488c7ab193cfe25"
      define_method(:install) do
        bin.install "searchatlas"
      end
    end
  end

  test do
    system "#{bin}/searchatlas", "version"
  end
end
